os: linux
dist: xenial
language: java
jdk: openjdk8
sudo: required

services:
- docker

cache:
  directories:
  - "$HOME/.gradle"

script: ./gradlew buildDockerImage check --info

deploy:
  provider: script
  script: ./gradlew buildDockerImage
  on:
    branch: master
