os: linux
dist: xenial
language: java
jdk: openjdk8
sudo: required

services:
- docker

cache:
  directories:
  - "$HOME/.gradle"

script: ./gradlew check --info

deploy:
  skip_cleanup: true
  provider: script
  script: ./gradlew pushDockerImage
  on:
    branch: master
